//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Fall2017Entities : DbContext
    {
        public Fall2017Entities()
            : base("name=Fall2017Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Breed> Breed { get; set; }
        public virtual DbSet<Carer> Carer { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<PetDetail> PetDetail { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
