//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PetDetail()
        {
            this.Carer = new HashSet<Carer>();
        }
    
        public string PetID { get; set; }
        public string PetName { get; set; }
        public int Species { get; set; }
        public int Breed { get; set; }
        public bool Gender { get; set; }
        public Nullable<System.DateTime> DayOfBirth { get; set; }
        public string OwnerID { get; set; }
        public System.DateTime InDate { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public string MedicalRecord { get; set; }
        public bool Status { get; set; }
    
        public virtual Breed Breed1 { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual Species Species1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carer> Carer { get; set; }
    }
}
